r"""
    This code was generated by
  ___ ___   _   ___ _  _    _____ _   _    _  ___   ___      _   ___ ___      ___   _   ___     ___ ___ _  _ ___ ___    _ _____ ___  ___ 
 | _ \ __| /_\ / __| || |__|_   _/_\ | |  | |/ | \ / / |    /_\ | _ ) __|___ / _ \ /_\ |_ _|__ / __| __| \| | __| _ \  /_\_   _/ _ \| _ \
 |   / _| / _ \ (__| __ |___|| |/ _ \| |__| ' < \ V /| |__ / _ \| _ \__ \___| (_) / _ \ | |___| (_ | _|| .` | _||   / / _ \| || (_) |   /
 |_|_\___/_/ \_\___|_||_|    |_/_/ \_\____|_|\_\ |_| |____/_/ \_\___/___/    \___/_/ \_\___|   \___|___|_|\_|___|_|_\/_/ \_\_| \___/|_|_\
 
    Reach Messaging API
    Reach SMS API helps you add robust messaging capabilities to your applications.  Using this REST API, you can * send SMS messages * track the delivery of sent messages * schedule SMS messages to send at a later time * retrieve and modify message history

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""

from typing import Optional
from talkylabs.reach.base.version import Version
from talkylabs.reach.base.domain import Domain
from talkylabs.reach.rest.api.messaging.messaging_item import MessagingItemList


class Messaging(Version):

    def __init__(self, domain: Domain):
        """
        Initialize the Messaging version of Api

        :param domain: The Reach.api domain
        """
        super().__init__(domain, "rest")
        self._messaging_items: Optional[MessagingItemList] = None
        
    @property
    def messaging_items(self) -> MessagingItemList:
        if self._messaging_items is None:
            self._messaging_items = MessagingItemList(self)
        return self._messaging_items

    def __repr__(self) -> str:
        """
        Provide a friendly representation
        :returns: Machine friendly representation
        """
        return "<Reach.Api.Messaging>"
