r"""
  This code was generated by
  ___ ___   _   ___ _  _    _____ _   _    _  ___   ___      _   ___ ___      ___   _   ___     ___ ___ _  _ ___ ___    _ _____ ___  ___ 
 | _ \ __| /_\ / __| || |__|_   _/_\ | |  | |/ | \ / / |    /_\ | _ ) __|___ / _ \ /_\ |_ _|__ / __| __| \| | __| _ \  /_\_   _/ _ \| _ \
 |   / _| / _ \ (__| __ |___|| |/ _ \| |__| ' < \ V /| |__ / _ \| _ \__ \___| (_) / _ \ | |___| (_ | _|| .` | _||   / / _ \| || (_) |   /
 |_|_\___/_/ \_\___|_||_|    |_/_/ \_\____|_|\_\ |_| |____/_/ \_\___/___/    \___/_/ \_\___|   \___|___|_|\_|___|_|_\/_/ \_\_| \___/|_|_\
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

from typing import Optional

from talkylabs.reach.base.domain import Domain
from talkylabs.reach.rest import ReachClient
from talkylabs.reach.rest.api.messaging import Messaging
from talkylabs.reach.rest.api.authentix import Authentix


class ApiBase(Domain):
    def __init__(self, reach: ReachClient):
        """
        Initialize the Api Domain

        :returns: Domain for Api
        """
        super().__init__(reach, "https://api.reach.talkylabs.com")
        self._messaging: Optional[Messaging] = None
        self._authentix: Optional[Authentix] = None

    @property
    def messaging(self) -> Messaging:
        """
        :returns: the Messaging Api
        """
        if self._messaging is None:
            self._messaging = Messaging(self)
        return self._messaging

    @property
    def authentix(self) -> Authentix:
        """
        :returns: the Authentix Api
        """
        if self._authentix is None:
            self._authentix = Authentix(self)
        return self._authentix

    def __repr__(self) -> str:
        """
        Provide a friendly representation
        :returns: Machine friendly representation
        """
        return "<Reach.Api>"
